/**
 * region-labels.ts
 *
 * Human-readable region labels for all cloud providers.
 * Used to enrich index.json manifest with friendly names.
 */

export const REGION_LABELS: Record<string, Record<string, string>> = {
  aws: {
    "af-south-1": "Africa (Cape Town)",
    "ap-east-1": "Asia Pacific (Hong Kong)",
    "ap-east-2": "Asia Pacific (Hyderabad)",
    "ap-northeast-1": "Asia Pacific (Tokyo)",
    "ap-northeast-2": "Asia Pacific (Seoul)",
    "ap-northeast-3": "Asia Pacific (Osaka)",
    "ap-south-1": "Asia Pacific (Mumbai)",
    "ap-south-2": "Asia Pacific (Hyderabad)",
    "ap-southeast-1": "Asia Pacific (Singapore)",
    "ap-southeast-2": "Asia Pacific (Sydney)",
    "ap-southeast-3": "Asia Pacific (Jakarta)",
    "ap-southeast-4": "Asia Pacific (Melbourne)",
    "ap-southeast-5": "Asia Pacific (Malaysia)",
    "ap-southeast-6": "Asia Pacific (Thailand)",
    "ap-southeast-7": "Asia Pacific (Auckland)",
    "ca-central-1": "Canada (Central)",
    "ca-west-1": "Canada West (Calgary)",
    "eu-central-1": "Europe (Frankfurt)",
    "eu-central-2": "Europe (Zurich)",
    "eu-north-1": "Europe (Stockholm)",
    "eu-south-1": "Europe (Milan)",
    "eu-south-2": "Europe (Spain)",
    "eu-west-1": "Europe (Ireland)",
    "eu-west-2": "Europe (London)",
    "eu-west-3": "Europe (Paris)",
    "il-central-1": "Middle East (Israel)",
    "me-central-1": "Middle East (UAE)",
    "me-south-1": "Middle East (Bahrain)",
    "mx-central-1": "Mexico (Central)",
    "sa-east-1": "South America (São Paulo)",
    "us-east-1": "US East (N. Virginia)",
    "us-east-2": "US East (Ohio)",
    "us-gov-east-1": "AWS GovCloud (US-East)",
    "us-gov-west-1": "AWS GovCloud (US-West)",
    "us-west-1": "US West (N. California)",
    "us-west-2": "US West (Oregon)",
  },
  azure: {
    australiacentral: "Australia Central",
    australiacentral2: "Australia Central 2",
    australiaeast: "Australia East",
    australiasoutheast: "Australia Southeast",
    austriaeast: "Austria East",
    belgiumcentral: "Belgium Central",
    brazilsouth: "Brazil South",
    brazilsoutheast: "Brazil Southeast",
    canadacentral: "Canada Central",
    canadaeast: "Canada East",
    centralindia: "Central India",
    centralus: "Central US",
    chilecentral: "Chile Central",
    eastasia: "East Asia",
    eastus: "East US",
    eastus2: "East US 2",
    francecentral: "France Central",
    francesouth: "France South",
    germanynorth: "Germany North",
    germanywestcentral: "Germany West Central",
    indonesiacentral: "Indonesia Central",
    israelcentral: "Israel Central",
    italynorth: "Italy North",
    japaneast: "Japan East",
    japanwest: "Japan West",
    koreacentral: "Korea Central",
    koreasouth: "Korea South",
    malaysiawest: "Malaysia West",
    mexicocentral: "Mexico Central",
    newzealandnorth: "New Zealand North",
    northcentralus: "North Central US",
    northeurope: "North Europe",
    norwayeast: "Norway East",
    norwaywest: "Norway West",
    polandcentral: "Poland Central",
    qatarcentral: "Qatar Central",
    southafricanorth: "South Africa North",
    southafricawest: "South Africa West",
    southcentralus: "South Central US",
    southeastasia: "Southeast Asia",
    southindia: "South India",
    spaincentral: "Spain Central",
    swedencentral: "Sweden Central",
    switzerlandnorth: "Switzerland North",
    switzerlandwest: "Switzerland West",
    uaecentral: "UAE Central",
    uaenorth: "UAE North",
    uksouth: "UK South",
    ukwest: "UK West",
    westcentralus: "West Central US",
    westeurope: "West Europe",
    westindia: "West India",
    westus: "West US",
    westus2: "West US 2",
    westus3: "West US 3",
  },
  gcp: {
    "africa-south1": "Africa South (Johannesburg)",
    "asia-east1": "Asia East (Taiwan)",
    "asia-east2": "Asia East (Hong Kong)",
    "asia-northeast1": "Asia Northeast (Tokyo)",
    "asia-northeast2": "Asia Northeast (Osaka)",
    "asia-northeast3": "Asia Northeast (Seoul)",
    "asia-south1": "Asia South (Mumbai)",
    "asia-south2": "Asia South (Delhi)",
    "asia-southeast1": "Asia Southeast (Singapore)",
    "asia-southeast2": "Asia Southeast (Jakarta)",
    "australia-southeast1": "Australia Southeast (Sydney)",
    "australia-southeast2": "Australia Southeast (Melbourne)",
    "europe-central2": "Europe Central (Warsaw)",
    "europe-north1": "Europe North (Finland)",
    "europe-north2": "Europe North (Stockholm)",
    "europe-southwest1": "Europe Southwest (Madrid)",
    "europe-west1": "Europe West (Belgium)",
    "europe-west2": "Europe West (London)",
    "europe-west3": "Europe West (Frankfurt)",
    "europe-west4": "Europe West (Netherlands)",
    "europe-west6": "Europe West (Zurich)",
    "europe-west8": "Europe West (Milan)",
    "europe-west9": "Europe West (Paris)",
    "europe-west10": "Europe West (Berlin)",
    "europe-west12": "Europe West (Turin)",
    "me-central1": "Middle East Central (Doha)",
    "me-central2": "Middle East Central (Dammam)",
    "me-west1": "Middle East West (Tel Aviv)",
    "northamerica-northeast1": "North America (Montréal)",
    "northamerica-northeast2": "North America (Toronto)",
    "northamerica-south1": "North America (Mexico)",
    "southamerica-east1": "South America (São Paulo)",
    "southamerica-west1": "South America (Santiago)",
    "us-central1": "US Central (Iowa)",
    "us-east1": "US East (S. Carolina)",
    "us-east4": "US East (N. Virginia)",
    "us-east5": "US East (Columbus)",
    "us-south1": "US South (Dallas)",
    "us-west1": "US West (Oregon)",
    "us-west2": "US West (Los Angeles)",
    "us-west3": "US West (Salt Lake City)",
    "us-west4": "US West (Las Vegas)",
  },
};

/**
 * Get a human-readable label for a region, or fall back to the region ID.
 */
export function getRegionLabel(provider: string, regionId: string): string {
  return REGION_LABELS[provider]?.[regionId] || regionId;
}
